export const DECISION_OUTCOME = {
  ALLOWED: 'ALLOWED',
  REJECTED: 'REJECTED',
  BLOCKED: 'BLOCKED',
  DEGRADED_ALLOWED: 'DEGRADED_ALLOWED',
  DEGRADED_REJECTED: 'DEGRADED_REJECTED',
} as const;

export type DecisionOutcome = (typeof DECISION_OUTCOME)[keyof typeof DECISION_OUTCOME];
